# Generated by Django 5.2 on 2025-05-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="discription",
            new_name="description",
        ),
    ]
